Limit doc str first line length to 80 chars
Recent snapshot builds of Emacs 28.0.50 now seem to cause byte
compiler errors like:

  Error: custom-declare-variable `x' docstring wider than 80 characters