Avoid "fancy" single quotation marks error added in Emacs 29.0.50
For things like

  ‘nil’

the error message is

  Error: docstring has wrong usage of "fancy" single quotation marks

Resolve by changing to "nil" or just (no quotes) nil.

Also, things like 'foo in a doc string will elicit this error. The fix
is to use the \\= prefix, e.g. \\='foo.